# Generated by Django 3.1.5 on 2021-02-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0003_remove_profile_comment_created_by'),
        ('post', '0003_auto_20210215_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_created_by', to='profile.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='post.post')),
            ],
            options={
                'db_table': 'followings',
                'unique_together': {('created_by', 'user')},
            },
        ),
    ]
