# Generated by Django 3.1.5 on 2021-02-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_profile_comment_created_by'),
        ('post', '0003_auto_20210215_1801'),
        ('followings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='Followings',
        ),
    ]
