# Generated by Django 3.1.5 on 2021-02-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_profile_comment_created_by'),
        ('followings', '0002_auto_20210220_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='profile.profile'),
        ),
    ]
