# Generated by Django 3.1.5 on 2021-04-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postforum', '0001_initial'),
        ('profile', '0006_auto_20210415_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForumComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_forum_created_by', to='profile.profile')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_forum_id', to='postforum.postforum')),
            ],
            options={
                'db_table': 'postforumcomment',
            },
        ),
    ]
