# Generated by Django 3.1.5 on 2021-04-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postforumcomments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postforumcomments',
            old_name='post_id',
            new_name='post_forum_id',
        ),
    ]
