# Generated by Django 3.1.5 on 2021-04-16 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postforumcomments', '0002_auto_20210416_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforumcomments',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 14, 30, 39, 42561)),
        ),
    ]
