# Generated by Django 3.1.5 on 2021-02-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_profile_comment_created_by'),
        ('postcomments', '0002_postcomments_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_created_by', to='profile.profile'),
        ),
    ]
