# Generated by Django 3.1.5 on 2021-03-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210215_1801'),
        ('postcomments', '0003_auto_20210215_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_id', to='post.post'),
        ),
    ]
