# Generated by Django 3.1.5 on 2021-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postforum', '0001_initial'),
        ('profile', '0006_auto_20210415_0845'),
        ('postforumlikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforumlikes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post_forum_created_by', to='profile.profile'),
        ),
        migrations.AlterField(
            model_name='postforumlikes',
            name='post_forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_post_forum_id', to='postforum.postforum'),
        ),
        migrations.AlterUniqueTogether(
            name='postforumlikes',
            unique_together={('created_by', 'post_forum_id')},
        ),
    ]
