# Generated by Django 3.1.5 on 2021-02-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_comment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment_created_by',
        ),
    ]
