# Generated by Django 3.1.5 on 2021-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20210406_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_latitude',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_longitude',
            field=models.FloatField(default=20.0),
        ),
    ]
