# Generated by Django 3.1.5 on 2021-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20210411_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.TextField(default='https://profiles.utdallas.edu/img/default.png'),
        ),
    ]
