# Generated by Django 3.1.5 on 2021-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0006_auto_20210415_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_forum_created_by', to='profile.profile')),
            ],
            options={
                'verbose_name_plural': 'PostsForum',
                'db_table': 'postforum',
            },
        ),
    ]
