# Generated by Django 3.1.5 on 2021-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210215_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
