# Generated by Django 3.1.5 on 2021-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateField(default='2020-02-02'),
            preserve_default=False,
        ),
    ]
