# Generated by Django 3.1.5 on 2021-04-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='creation_date',
        ),
    ]
