# Generated by Django 3.1.5 on 2021-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210406_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
